# Generated by Django 4.1.2 on 2022-11-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studysessionmodel_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject_field',
            field=models.CharField(default='subject', max_length=10),
        ),
    ]
