# Generated by Django 4.1.2 on 2022-11-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studysessionmodel_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysessionmodel',
            name='class_name',
            field=models.CharField(default='CS1110', max_length=200),
            preserve_default=False,
        ),
    ]
