# Generated by Django 4.1.2 on 2022-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_class_subject_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Enrolled_Courses',
        ),
        migrations.AddField(
            model_name='profile',
            name='Enrolled_Courses',
            field=models.ManyToManyField(blank=True, to='app.class'),
        ),
    ]
