# Generated by Django 4.1.2 on 2022-11-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_class_description_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='catalog_number_field',
            field=models.CharField(default='catalog', max_length=10),
        ),
    ]
