# Generated by Django 4.1.2 on 2022-11-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_class_catalog_number_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Enrolled_Courses',
            field=models.ManyToManyField(blank=True, to='app.class'),
        ),
    ]
