# Generated by Django 4.1.2 on 2022-11-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studysessionmodel_class_name'),
        ('app', '0007_alter_profile_bio_alter_profile_enrolled_courses'),
    ]

    operations = [
    ]
