# Generated by Django 4.1.2 on 2022-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessionmodel',
            name='class_name',
            field=models.CharField(choices=[], max_length=200),
        ),
    ]
