# Generated by Django 4.1.2 on 2022-11-13 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_studysessionmodel_class_name'),
        ('app', '0011_profile_following'),
    ]

    operations = [
    ]
