# Generated by Django 4.1.2 on 2022-12-06 23:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_discussions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessionmodel',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
